[package]
name = "fkm-proxy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fkm-proxy-client"
path = "src/client/main.rs"

[[bin]]
name = "fkm-proxy-server"
path = "src/server/main.rs"

[dependencies]
anyhow = "1.0.95"
highway = "1.3.0"
kanal = "0.1.0-pre8"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tokio-rustls = { version = "0.26.1", features = ["ring", "logging", "tls12"], default-features = false }
clap = { version = "4.5.29", features = ["derive", "env"] }
dotenvy = "0.15.7"
rcgen = "0.13.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"

utils = { path = "./utils" }
qls-proto-utils = "0.2.0"

[profile.release]
opt-level = "z"     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = "abort"     # Abort on panic
strip = true        # Automatically strip symbols from the binary.
