[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
rustls-pemfile = "2.1.1"
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full"] }
tokio-rustls = { version = "0.26.0", features = ["logging", "tls12"], default-features = false }
